create table if not exists hxb_dh_data_ads.ads_deposit_branch_sales_fee_wide_new
(
    branch_no                string comment '机构号',
    branch_name              string comment '机构名称',
    deposit_type             string comment '存款类型',
    end_fee                  decimal(30, 8) comment '最终存量费用',
    end_fee_i_1              decimal(30, 8) comment '最终增量费用调节系数1',
    end_fee_i_11             decimal(30, 8) comment '最终增量费用调节系数11',
    end_fee_i_12             decimal(30, 8) comment '最终增量费用调节系数12',
    end_fee_sum              decimal(30, 8) comment '最终总费用',
    fee                      decimal(30, 8) comment '减之前存量费用',
    fee_i_1                  decimal(30, 8) comment '减之前增量费用调节系数1',
    fee_i_11                 decimal(30, 8) comment '减之前增量费用调节系数11',
    fee_i_12                 decimal(30, 8) comment '减之前增量费用调节系数12',
    fee_sum                  decimal(30, 8) comment '减之前总费用',
    last_fee                 decimal(30, 8) comment '本季之前存量费用',
    last_fee_i_1             decimal(30, 8) comment '本季之前增量费用调节系数1',
    last_fee_i_11            decimal(30, 8) comment '本季之前增量费用调节系数11',
    last_fee_i_12            decimal(30, 8) comment '本季之前增量费用调节系数12',
    last_fee_sum             decimal(30, 8) comment '本季之前总费用',

    head_rate                decimal(30, 8) comment '与总行日均存量折比例',
    head_rate_i              decimal(30, 8) comment '与总行日均增量折比例',
    last_year_avg_bal_r      decimal(30, 8) comment '基础存款去年日均',
    -- curr_quarter_avg_bal_r      decimal(30, 8) comment '基础存款当季日均',
    curr_year_avg_bal_r      decimal(30, 8) comment '基础存款当年年日均',
    avg_bal_r                decimal(30, 8) comment '基础存款日均存量',
    avg_bal_r_i              decimal(30, 8) comment '基础存款日均增量',
    hq_last_year_avg_bal_r   decimal(30, 8) comment '基础存款活期去年日均',
    -- hq_curr_quarter_avg_bal_r   decimal(30, 8) comment '基础存款活期当季日均',
    hq_curr_year_avg_bal_r   decimal(30, 8) comment '基础存款活期当年年日均',
    hq_avg_bal_r             decimal(30, 8) comment '基础存款活期日均存量',
    hq_avg_bal_r_i           decimal(30, 8) comment '基础存款活期日均增量',

    hq01_rate_std            decimal(30, 8) comment '活期不超过挂牌利率存量费率标准',
    hq01_rate_std_i          decimal(30, 8) comment '活期不超过挂牌利率增量费率标准',
    hq01_last_year_avg_bal_r decimal(30, 8) comment '基础存款活期不超过挂牌利率去年日均',
    -- hq01_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款活期不超过挂牌利率当季日均',
    hq01_curr_year_avg_bal_r decimal(30, 8) comment '基础存款活期不超过挂牌利率当年年日均',
    hq01_avg_bal_r           decimal(30, 8) comment '基础存款活期不超过挂牌利率存量日均',
    hq01_avg_bal_r_i         decimal(30, 8) comment '基础存款活期不超过挂牌利率增量日均',
    hq01_avg_bal_r_flod      decimal(30, 8) comment '活期不超过挂牌利率折后日均存量',
    hq01_avg_bal_r_flod_i    decimal(30, 8) comment '活期不超过挂牌利率折后日均增量',

    hq01_end_fee             decimal(30, 8) comment '活期不超过挂牌利率最终存量费用',
    hq01_end_fee_i_1         decimal(30, 8) comment '活期不超过挂牌利率最终增量费用调节系数1',
    hq01_end_fee_i_11        decimal(30, 8) comment '活期不超过挂牌利率最终增量费用调节系数11',
    hq01_end_fee_i_12        decimal(30, 8) comment '活期不超过挂牌利率最终增量费用调节系数12',
    hq01_fee                 decimal(30, 8) comment '活期不超过挂牌利率减之前存量费用',
    hq01_fee_i_1             decimal(30, 8) comment '活期不超过挂牌利率减之前增量费用调节系数1',
    hq01_fee_i_11            decimal(30, 8) comment '活期不超过挂牌利率减之前增量费用调节系数11',
    hq01_fee_i_12            decimal(30, 8) comment '活期不超过挂牌利率减之前增量费用调节系数12',
    hq01_last_fee            decimal(30, 8) comment '活期不超过挂牌利率本季之前存量费用',
    hq01_last_fee_i_1        decimal(30, 8) comment '活期不超过挂牌利率本季之前增量费用调节系数1',
    hq01_last_fee_i_11       decimal(30, 8) comment '活期不超过挂牌利率本季之前增量费用调节系数11',
    hq01_last_fee_i_12       decimal(30, 8) comment '活期不超过挂牌利率本季之前增量费用调节系数12',

    hq02_rate_std            decimal(30, 8) comment '活期不超过央行基准利率加点20bp存量费率标准',
    hq02_rate_std_i          decimal(30, 8) comment '活期不超过央行基准利率加点20bp增量费率标准',
    hq02_last_year_avg_bal_r decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp去年日均',
    -- hq02_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp当季日均',
    hq02_curr_year_avg_bal_r decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp当年年日均',
    hq02_year_avg_bal_r      decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp存量日均',
    hq02_year_avg_bal_r_i    decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp增量日均',
    hq02_avg_bal_r_flod      decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp折后日均存量',
    hq02_avg_bal_r_flod_i    decimal(30, 8) comment '基础存款活期不超过央行基准利率加点20bp折后日均增量',

    hq02_end_fee             decimal(30, 8) comment '活期不超过央行基准利率加点20bp最终存量费用',
    hq02_end_fee_i_1         decimal(30, 8) comment '活期不超过央行基准利率加点20bp最终增量费用调节系数1',
    hq02_end_fee_i_11        decimal(30, 8) comment '活期不超过央行基准利率加点20bp最终增量费用调节系数11',
    hq02_end_fee_i_12        decimal(30, 8) comment '活期不超过央行基准利率加点20bp最终增量费用调节系数12',
    hq02_fee                 decimal(30, 8) comment '活期不超过央行基准利率加点20bp减之前存量费用',
    hq02_fee_i_1             decimal(30, 8) comment '活期不超过央行基准利率加点20bp减之前增量费用调节系数1',
    hq02_fee_i_11            decimal(30, 8) comment '活期不超过央行基准利率加点20bp减之前增量费用调节系数11',
    hq02_fee_i_12            decimal(30, 8) comment '活期不超过央行基准利率加点20bp减之前增量费用调节系数12',
    hq02_last_fee            decimal(30, 8) comment '活期不超过央行基准利率加点20bp本季之前存量费用',
    hq02_last_fee_i_1        decimal(30, 8) comment '活期不超过央行基准利率加点20bp本季之前增量费用调节系数1',
    hq02_last_fee_i_11       decimal(30, 8) comment '活期不超过央行基准利率加点20bp本季之前增量费用调节系数11',
    hq02_last_fee_i_12       decimal(30, 8) comment '活期不超过央行基准利率加点20bp本季之前增量费用调节系数12',

    dq_last_year_avg_bal_r   decimal(30, 8) comment '基础存款(定期/协定)去年日均',
    -- dq_curr_quarter_avg_bal_r   decimal(30, 8) comment '基础存款(定期/协定)当季日均',
    dq_curr_year_avg_bal_r   decimal(30, 8) comment '基础存款(定期/协定)当年年日均',
    dq_avg_bal_r             decimal(30, 8) comment '基础存款(定期/协定)存量日均',
    dq_avg_bal_r_i           decimal(30, 8) comment '基础存款(定期/协定)增量日均',

    dq01_rate_std            decimal(30, 8) comment '(定期/协定)不超过挂牌利率存量费率标准',
    dq01_rate_std_i          decimal(30, 8) comment '(定期/协定)不超过挂牌利率增量费率标准',
    dq01_last_year_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过挂牌利率去年日均',
    -- dq01_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过挂牌利率当季日均',
    dq01_curr_year_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过挂牌利率当年年日均',
    dq01_avg_bal_r           decimal(30, 8) comment '基础存款(定期/协定)不超过挂牌利率存量日均',
    dq01_avg_bal_r_i         decimal(30, 8) comment '基础存款(定期/协定)不超过挂牌利率增量日均',
    dq01_avg_bal_r_flod      decimal(30, 8) comment '(定期/协定)不超过挂牌利率折后日均存量',
    dq01_avg_bal_r_flod_i    decimal(30, 8) comment '(定期/协定)不超过挂牌利率折后日均增量',

    dq01_end_fee             decimal(30, 8) comment '(定期/协定)不超过挂牌利率最终存量费用',
    dq01_end_fee_i_1         decimal(30, 8) comment '(定期/协定)不超过挂牌利率最终增量费用调节系数1',
    dq01_end_fee_i_11        decimal(30, 8) comment '(定期/协定)不超过挂牌利率最终增量费用调节系数11',
    dq01_end_fee_i_12        decimal(30, 8) comment '(定期/协定)不超过挂牌利率最终增量费用调节系数12',
    dq01_fee                 decimal(30, 8) comment '(定期/协定)不超过挂牌利率减之前存量费用',
    dq01_fee_i_1             decimal(30, 8) comment '(定期/协定)不超过挂牌利率减之前增量费用调节系数1',
    dq01_fee_i_11            decimal(30, 8) comment '(定期/协定)不超过挂牌利率减之前增量费用调节系数11',
    dq01_fee_i_12            decimal(30, 8) comment '(定期/协定)不超过挂牌利率减之前增量费用调节系数12',
    dq01_last_fee            decimal(30, 8) comment '(定期/协定)不超过挂牌利率本季之前存量费用',
    dq01_last_fee_i_1        decimal(30, 8) comment '(定期/协定)不超过挂牌利率本季之前增量费用调节系数1',
    dq01_last_fee_i_11       decimal(30, 8) comment '(定期/协定)不超过挂牌利率本季之前增量费用调节系数11',
    dq01_last_fee_i_12       decimal(30, 8) comment '(定期/协定)不超过挂牌利率本季之前增量费用调节系数12',

    dq02_rate_std            decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp存量费率标准',
    dq02_rate_std_i          decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp增量费率标准',
    dq02_last_year_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过央行基准利率加点20bp去年日均',
    -- dq02_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过央行基准利率加点20bp当季日均',
    dq02_curr_year_avg_bal_r decimal(30, 8) comment '基础存款(定期/协定)不超过央行基准利率加点20bp当年年日均',
    dq02_avg_bal_r           decimal(30, 8) comment '基础存款(定期/协定)不超过央行基准利率加点20bp存量日均',
    dq02_avg_bal_r_i         decimal(30, 8) comment '基础存款(定期/协定)不超过央行基准利率加点20bp增量日均',
    dq02_avg_bal_r_flod      decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp折后日均存量',
    dq02_avg_bal_r_flod_i    decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp折后日均增量',

    dq02_end_fee             decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp最终存量费用',
    dq02_end_fee_i_1         decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp最终增量费用调节系数1',
    dq02_end_fee_i_11        decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp最终增量费用调节系数11',
    dq02_end_fee_i_12        decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp最终增量费用调节系数12',
    dq02_fee                 decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp减之前存量费用',
    dq02_fee_i_1             decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp减之前增量费用调节系数1',
    dq02_fee_i_11            decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp减之前增量费用调节系数11',
    dq02_fee_i_12            decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp减之前增量费用调节系数12',
    dq02_last_fee            decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp本季之前存量费用',
    dq02_last_fee_i_1        decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp本季之前增量费用调节系数1',
    dq02_last_fee_i_11       decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp本季之前增量费用调节系数11',
    dq02_last_fee_i_12       decimal(30, 8) comment '(定期/协定)不超过央行基准利率加点20bp本季之前增量费用调节系数12',

    dq03_rate_std            decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单存量费率标准',
    dq03_rate_std_i          decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单增量费率标准',
    dq03_last_year_avg_bal_r decimal(30, 8) comment '基础存款定期两年及以内的加点不超过80个bp的个人大额存单去年日均',
    -- dq03_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款定期两年及以内的加点不超过80个bp的个人大额存单当季日均',
    dq03_curr_year_avg_bal_r decimal(30, 8) comment '基础存款定期两年及以内的加点不超过80个bp的个人大额存单当年年日均',
    dq03_avg_bal_r           decimal(30, 8) comment '基础存款定期两年及以内的加点不超过80个bp的个人大额存单存量日均',
    dq03_avg_bal_r_i         decimal(30, 8) comment '基础存款定期两年及以内的加点不超过80个bp的个人大额存单增量日均',
    dq03_avg_bal_r_flod      decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单折后日均存量',
    dq03_avg_bal_r_flod_i    decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单折后日均增量',

    dq03_end_fee             decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单最终存量费用',
    dq03_end_fee_i_1         decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单最终增量费用调节系数1',
    dq03_end_fee_i_11        decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单最终增量费用调节系数11',
    dq03_end_fee_i_12        decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单最终增量费用调节系数12',
    dq03_fee                 decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单减之前存量费用',
    dq03_fee_i_1             decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单减之前增量费用调节系数1',
    dq03_fee_i_11            decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单减之前增量费用调节系数11',
    dq03_fee_i_12            decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单减之前增量费用调节系数12',
    dq03_last_fee            decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单本季之前存量费用',
    dq03_last_fee_i_1        decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单本季之前增量费用调节系数1',
    dq03_last_fee_i_11       decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单本季之前增量费用调节系数11',
    dq03_last_fee_i_12       decimal(30, 8) comment '定期两年及以内的加点不超过80个bp的个人大额存单本季之前增量费用调节系数12',

    wb_last_year_avg_bal_r   decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)去年日均',
    -- wb_curr_quarter_avg_bal_r   decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)当季日均',
    wb_curr_year_avg_bal_r   decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)当年年日均',
    wb_avg_bal_r             decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)存量日均',
    wb_avg_bal_r_i           decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)增量日均',

    wb01_rate_std            decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)存量费率标准',
    wb01_rate_std_i          decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)增量费率标准',
    wb01_last_year_avg_bal_r decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)去年日均',
    -- wb01_curr_quarter_avg_bal_r decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)当季日均',
    wb01_curr_year_avg_bal_r decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)当年年日均',
    wb01_avg_bal_r           decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)存量日均',
    wb01_avg_bal_r_i         decimal(30, 8) comment '基础存款(外币一年期及以内/外币活期)增量日均',
    wb01_avg_bal_r_flod      decimal(30, 8) comment '(外币一年期及以内/外币活期)折后日均存量',
    wb01_avg_bal_r_flod_i    decimal(30, 8) comment '(外币一年期及以内/外币活期)折后日均增量',

    wb01_end_fee             decimal(30, 8) comment '(外币一年期及以内/外币活期)最终存量费用',
    wb01_end_fee_i_1         decimal(30, 8) comment '(外币一年期及以内/外币活期)最终增量费用调节系数1',
    wb01_end_fee_i_11        decimal(30, 8) comment '(外币一年期及以内/外币活期)最终增量费用调节系数11',
    wb01_end_fee_i_12        decimal(30, 8) comment '(外币一年期及以内/外币活期)最终增量费用调节系数12',
    wb01_fee                 decimal(30, 8) comment '(外币一年期及以内/外币活期)减之前存量费用',
    wb01_fee_i_1             decimal(30, 8) comment '(外币一年期及以内/外币活期)减之前增量费用调节系数1',
    wb01_fee_i_11            decimal(30, 8) comment '(外币一年期及以内/外币活期)减之前增量费用调节系数11',
    wb01_fee_i_12            decimal(30, 8) comment '(外币一年期及以内/外币活期)减之前增量费用调节系数12',
    wb01_last_fee            decimal(30, 8) comment '(外币一年期及以内/外币活期)本季之前存量费用',
    wb01_last_fee_i_1        decimal(30, 8) comment '(外币一年期及以内/外币活期)本季之前增量费用调节系数1',
    wb01_last_fee_i_11       decimal(30, 8) comment '(外币一年期及以内/外币活期)本季之前增量费用调节系数11',
    wb01_last_fee_i_12       decimal(30, 8) comment '(外币一年期及以内/外币活期)本季之前增量费用调节系数12'
    ) using orc partitioned by (etl_date date) comment '机构基础存款-销售费用-宽表';
