create table if not exists hxb_dh_data_dws.dws_deposit_branch_sales_fee
(
    branch_no             string comment '机构号',
    branch_name           string comment '机构名称',
    deposit_type          string comment '存款类型',
    pro_type              string comment '产品类型-总类',
    rate_des              string comment '利率描述',
    rate_std              decimal(10, 8) comment '存量费率标准',
    rate_std_i            decimal(10, 8) comment '增量费率标准',
    head_rate             decimal(10, 8) comment '与总行日均存量折比例',
    head_rate_i           decimal(10, 8) comment '与总行日均增量折比例',
    last_year_avg_bal_r_1 decimal(30, 6) comment '上年日均',
    -- curr_quarter_avg_bal_r_1 decimal(30, 6) comment '季日均',
    curr_year_avg_bal_r_1 decimal(30, 6) comment '当前年日均',
    avg_bal_r_1           decimal(30, 6) comment '总日均存量',
    avg_bal_r_i_1         decimal(30, 6) comment '总日均增量',
    last_year_avg_bal_r_2 decimal(30, 6) comment '产品类型上年日均',
    --curr_quarter_avg_bal_r_2 decimal(30, 6) comment '产品类型季日均',
    curr_year_avg_bal_r_2 decimal(30, 6) comment '产品类型年日均',
    avg_bal_r_2           decimal(30, 6) comment '产品类型日均存量',
    avg_bal_r_i_2         decimal(30, 6) comment '产品类型日均增量',
    avg_bal_r_sum_2       decimal(30, 6) comment '不同产品类型日均存量汇总',
    avg_bal_r_i_sum_2     decimal(30, 6) comment '不同产品类型日均增量汇总',
    last_year_avg_bal_r_3 decimal(30, 6) comment '产品类型费率上年日均',
    --curr_quarter_avg_bal_r_3 decimal(30, 6) comment '产品类型费率季日均',
    curr_year_avg_bal_r_3 decimal(30, 6) comment '产品类型费率年日均',
    avg_bal_r_3           decimal(30, 6) comment '产品类型费率日均存量',
    avg_bal_r_i_3         decimal(30, 6) comment '产品类型费率日均增量',
    avg_bal_r_sum_3       decimal(30, 6) comment '同一产品类型不同费率日均存量',
    avg_bal_r_i_sum_3     decimal(30, 6) comment '同一产品类型不同费率日均增量',
    avg_bal_r_flod        decimal(30, 6) comment '折后日均存量',
    avg_bal_r_i_flod      decimal(30, 6) comment '折后日均增量',
    fee                   decimal(30, 6) comment '存量费用',
    fee_i_1               decimal(30, 6) comment '增量费用比例1',
    fee_i_11              decimal(30, 6) comment '增量费用比例1.1',
    fee_i_12              decimal(30, 6) comment '增量费用比例1.2'
    ) using orc partitioned by (etl_date date) comment '机构基础存款-销售费用-产品总类';
